name: "Update Price Data"

on:
  schedule:
    - cron: "0 0 */3 * *" # Runs every 3 days at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: true

      - name: Set up devkit
        uses: sablier-labs/devkit/actions/setup@main
        with:
          package-manager: bun

      - name: Fetch cryptocurrency prices
        env:
          COINGECKO_API_KEY_1: ${{ secrets.COINGECKO_API_KEY_1 }}
          COINGECKO_API_KEY_2: ${{ secrets.COINGECKO_API_KEY_2 }}
        run: just fetch-crypto all

      - name: Fetch forex rates
        env:
          CURRENCY_FREAKS_API_KEY: ${{ secrets.CURRENCY_FREAKS_API_KEY }}
        run: just fetch-forex

      - name: Verify changes
        run: |
          if ! git diff --quiet -- crypto/ forex/; then
            echo "✅ TSV files were updated"
            exit 0
          else
            echo "❌ No TSV files were updated - API fetch may have failed"
            exit 1
          fi

      - name: Generate timestamp
        id: timestamp
        run: echo "human=$(date '+%B %d, %Y at %H:%M UTC')" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add crypto/ forex/
          git commit -m "chore: update price data - ${{ steps.timestamp.outputs.human }}"
          git push

      - name: Add summary
        run: |
          echo "## Update result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Updated price data at ${{ steps.timestamp.outputs.human }}" >> $GITHUB_STEP_SUMMARY
